### ISSUE TITLE
Real IP not working

### ISSUE THREAD

**Issue by magrigry** [Azuriom/Plugin-CloudflareSupport#1]
I tested in different ways, and I noticed there is no way to get the real user IP from the `$request->ip()` method. 

In fact in TrustCloudflare::handle I see nothing that can update the IP in the parameter bag. 
Is there not something like `$request->server->set('REMOTE_ADDR', $request->header('CF-Connecting-IP'))` missing ?

**Comment by MrMicky-FR** [comment]
The `Request::setTrustedProxies` will rewrite IP when the request is from a Cloudflare server (see [Symfony documentation](https://symfony.com/doc/current/deployment/proxies.html)):
https://github.com/Azuriom/Plugin-CloudflareSupport/blob/ec257775275ce9bf70e7f04e93e8b357c4f241f2/src/Middleware/TrustCloudflare.php#L55 

What’s the output of `$request->ip()` ? A Cloudflare IP ?

**Comment by magrigry** [comment]
The result of `$request->ip()` is the IP of the docker container 172.23.0.1 (I am running Azuriom with the official docker-compose)
But If I add 
![image](https://user-images.githubusercontent.com/74878280/128226410-7bdf458a-4c78-4bc9-875c-041c2155cbf7.png)
Now I am getting the correct one 


While writting this, I just realized that it might be due to the fact that I am using an other proxy between Cloudflare and the Docker Container. Docker maybe also proxies something ? I don't know... 

Anyway the source IP is not replaced by CF-Connecting-IP because the source IP is not trusted
My solution works because it just bypass the trusted proxies which is not very good

**Comment by MrMicky-FR** [comment]
Yes, the ideal solution would be to configure Docker to forward the request ip.
Otherwise it’s also possible to replace `Request::setTrustedProxies($this->proxies, Request::HEADER_X_FORWARDED_ALL);` by `Request::setTrustedProxies(['REMOTE_ADDR'], Request::HEADER_X_FORWARDED_ALL);` which is nicer than changing the `REMOTE_ADDR` but this will rewrite the IP even if the request doesn’t come from Cloudflare which can lead to IP spoofing

**Comment by magrigry** [comment]
Yup, I just disallowed everything but Cloudflare IPs in my nginx config to avoid spoofing. I think I will stick with this dirty fix. 
Anyway thanks a lot for your help
