### ISSUE TITLE
Session expired (error 419)

### ISSUE THREAD

**Issue by Pluzdev** [Azuriom/Plugin-CloudflareSupport#3]
Good evening,
I have a problem with my website using cloudflare.
I put the plugin correctly but when I try to connect, I get a 419 error. (Page expired, try to reload the page and try again)
Do you have any idea how to solve this problem which blocks my whole site.

In desperation, I open this pull request. Thank you for your attention!

**Comment by MrMicky-FR** [comment]
Can you try to test if this issue also exists on your website without Cloudflare ? Because many Azuriom websites use Cloudflare without any issue

**Comment by Pluzdev** [comment]
Hello, There is no error when cloudflare is disabled.

**Comment by MrMicky-FR** [comment]
Make sure there is no Cloudflare cache for the HTML content on your website. Also can you send the URL of your website here or on Discord (MrMicky#5567 on https://azuriom.com/discord) ?

**Comment by Pluzdev** [comment]
I fixed the bug.. It was coming from my side! I had set the cache level to "all", I set it to standard and that fixed the problem. Sorry for inconvenience!
